name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: cicd/setup.sh

      - name: Test
        run: cicd/test.sh

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cicd/push_to_dockerhub.sh

      - name: Tag on Github
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cicd/tag_on_github.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cicd/publish_to_pypi.sh
        with:
          username: ${{ secrets.TWINE_USERNAME }}
          password: ${{ secrets.TWINE_PASSWORD }}

      - name: Upload Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports

  os_compatibility:
    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} Python: ${{ matrix.python-version }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10.0-rc.2", "pypy3"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel setuptools
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox -- --no-coverage
